### ISSUE TITLE
Chyba při hromadném importu FOXML

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius-admin-client#62]
Zdravím,

Při hromadném importu FOXML se stává, že proces skončí po pár vteřinách chybou. Pokud ale spustím import znovu, aniž bych cokoliv změnil, doběhne v pořádku až do konce.

Přidávám chybový výstup z importu 5 čísel periodika zpracovaného na ečlánky:
```
úno 13, 2023 6:56:01 ODP. cz.incad.kramerius.processes.starter.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at cz.incad.kramerius.processes.starter.ProcessStarter.main(ProcessStarter.java:125)
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot load relations: uuid:3f23934c-0d44-4325-8fea-e88b84992b0b
	at cz.incad.kramerius.service.impl.SortingServiceImpl.sortRelations(SortingServiceImpl.java:121)
	at org.kramerius.Import.run(Import.java:213)
	at org.kramerius.Import.main(Import.java:133)
	... 5 more
Caused by: java.io.IOException: Cannot load relations: uuid:3f23934c-0d44-4325-8fea-e88b84992b0b
	at cz.incad.kramerius.relation.impl.RelationServiceImpl.load(RelationServiceImpl.java:72)
	at cz.incad.kramerius.service.impl.SortingServiceImpl.sortRelations(SortingServiceImpl.java:87)
	... 7 more
Caused by: java.lang.RuntimeException: relation hasItem doesn't uniquely determine target object
	at cz.incad.kramerius.RDFModels.convertRDFToModel(RDFModels.java:27)
	at cz.incad.kramerius.relation.impl.RelationServiceImpl$Loader.processKrameriusElement(RelationServiceImpl.java:313)
	at cz.incad.kramerius.relation.impl.RelationServiceImpl$Loader.processElement(RelationServiceImpl.java:307)
	at cz.incad.kramerius.relation.impl.RelationServiceImpl$Loader.parse(RelationServiceImpl.java:297)
	at cz.incad.kramerius.relation.impl.RelationServiceImpl$Loader.load(RelationServiceImpl.java:275)
	at cz.incad.kramerius.relation.impl.RelationServiceImpl.load(RelationServiceImpl.java:70)
	... 8 more
```
Standardní výstup: [process_412_out.txt](https://github.com/ceskaexpedice/kramerius-admin-client/files/10724968/process_412_out.txt)  

testováno na k7Admin - verze: 1.4.0 - commit: [gef93035](https://github.com/ceskaexpedice/kramerius-admin-client/commit/gef93035) jádro - verze: 7.0.14 - commit: [e0136](https://github.com/ceskaexpedice/kramerius/commit/e01369245e01c8254835442aa56da968d6bcb2f3)

Díky!

**Comment by vlahoda** [comment]
Jako workaround by melo zafungovat nastaveni konfiguracni property ingest.sortRelations=false  (ta vyjimka vznika pri trideni vazeb v RELS-EXT, ktere je ale s novym klientem potreba uz jen pro stranky  (tedy doufam, jestli se zase neco nezmenilo ...)
