### ISSUE TITLE
Chyby při importování ve verzi 1.4.1.

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-admin-client#80]
V aktuální verzi 1.4.1. se mi děje dost neplechy ...

a) při importování periodik vždy dávka skončí s chybou:

```
May 23, 2023 5:00:00 PM cz.incad.kramerius.processes.starter.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at cz.incad.kramerius.processes.starter.ProcessStarter.main(ProcessStarter.java:127)
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot load relations: uuid:5ab0a9f6-18c6-465d-8c2d-117cc1c6247f
at cz.incad.kramerius.service.impl.SortingServiceImpl.sortRelations(SortingServiceImpl.java:121)
at org.kramerius.Import.run(Import.java:213)
at org.kramerius.importmets.MetsConvertor.run(MetsConvertor.java:140)
at org.kramerius.importmets.MetsConvertor.main(MetsConvertor.java:107)
... 5 more
Caused by: java.io.IOException: Cannot load relations: uuid:5ab0a9f6-18c6-465d-8c2d-117cc1c6247f
at cz.incad.kramerius.relation.impl.RelationServiceImpl.load(RelationServiceImpl.java:72)
at cz.incad.kramerius.service.impl.SortingServiceImpl.sortRelations(SortingServiceImpl.java:87)
... 8 more
Caused by: java.lang.RuntimeException: relation hasItem doesn't uniquely determine target object
at cz.incad.kramerius.RDFModels.convertRDFToModel(RDFModels.java:27)
at cz.incad.kramerius.relation.impl.RelationServiceImpl$Loader.processKrameriusElement(RelationServiceImpl.java:313)
at cz.incad.kramerius.relation.impl.RelationServiceImpl$Loader.processElement(RelationServiceImpl.java:307)
at cz.incad.kramerius.relation.impl.RelationServiceImpl$Loader.parse(RelationServiceImpl.java:297)
at cz.incad.kramerius.relation.impl.RelationServiceImpl$Loader.load(RelationServiceImpl.java:275)
at cz.incad.kramerius.relation.impl.RelationServiceImpl.load(RelationServiceImpl.java:70)
... 9 more

```

... pokud to reindexuju, tak se mi pak dokument normálně zobrazí. Postup je vždy takový, že pokud reindexuji zmíněné uuid v chybové hlášce, dostanu se v Krameriovi na nějakou součást periodika a můžu se z ní už prokliknout na titulové uuid, které ale vidím rozbité. Pokud dám reindex, vše se opraví. Nevím přesně, kde je chyba, ale není to úplně šťastné. (zde by mě mohl doplnit @stanislavteplik)

b) pokud je v dávce více dokumentů a objeví se chyba, spadne to úplně všechno - to by se podle mě dít nemělo, pokud je tam chyba, bylo by super, aby admin přeskočil importní soubor s chybou a zbytek normálně naimportoval, takto je to časově zbytečná detektivka, co zhavarovalo a co se možná nahrálo nebo taky možná nenahrálo (viz bod c)

c) mám tu asi objevený bug, který souvisí s #79 ... když jsem nahrávala výše zmíněnou část periodika, k tomu jsem se pokoušela nahrát i jednu monografii ... jelikož byla součástí té větší dávky, která skončila s chybou, do Krameria se ofiko nenahrála ... ale když jsem potom tu monografii nahrávala samostatně, nahrála se se zdvojenými stránkami - mám podezření, že při tom chybovém importu se přeci jen někde na pozadí něco nahraje a pak se to při pokusu o znovu importování takto zdvojí, tj. prosím o prověření

**Comment by pkudela** [comment]
@pavel-stastny tohle je asi na tebe ta chyba pri importu. @annie-cz co se tyce tech obrazku, tak z nejakeho duvodu nefunguji preklady, jakou verzi tam presne mas a zkousela si tvrdy reload CTRL+F5? Na vyvojovem serveru je to v poradku -> https://admin.k7.inovatika.dev/processes, tam je verze 7.0.23

**Comment by kerschfilip** [comment]
myslím, že se jedná o obdobný problém, který jsme hlásili v #62. Původně se nám to dělo jen u hromadného importu FOXML, ale ve verzi 1.4.1 je to nějak častější a děje se to i u jednotlivých NDK SIP balíčků periodik,

**Comment by honza-rychtar** [comment]
@pkudela aby se zabránilo potřebě hard reloadu na straně prohlížeče uživatele, uprav vždy při novém releasu url načítaného souboru s lokalizací, např. přes parametr s číslem verze.
https://github.com/ceskaexpedice/kramerius-admin-client/blob/43cf6a40330801dd6fd042509fc493b4a28a297f/src/app/app.module.ts#L102
Místo
```
return new TranslateHttpLoader(http, 'assets/i18n/', '.json');
```
použij
```
return new TranslateHttpLoader(http, 'assets/i18n/', '.json?v1.4.1');
```
v příštím releasu pak
```
return new TranslateHttpLoader(http, 'assets/i18n/', '.json?v1.4.2');
```
Tímto to bude pro prohlížeč vždy nový zdroj a nepoužije původní nakešovanou verzi.

**Comment by pkudela** [comment]
@honza-rychtar chapu, udelam, to uz jsem videl u web klienta, diky!

**Comment by annie-cz** [comment]
@pkudela Ikonky: Tak to bylo tím kešováním. Nicméně to, co tu píše Honza dává dost smysl, ne vždy člověka taková věc napadne, zvláště když se většina věcí zobrazuje správně.

**Comment by pkudela** [comment]
hotovo, zmena definice verze v settings -> nyni je to konstanta a ta se dosazuje vsude tam, kde je verze pouzita vcetne app.module.ts v metode pro preklad, otestovano

![image](https://github.com/ceskaexpedice/kramerius-admin-client/assets/16591052/5062fb12-ab36-4e3c-8029-af75df1317b5)
